### PR TITLE
Discovery on nested dtype numpy arrays and cleanup

### PR DESCRIPTION
**Pull request by cpcloud**
* record dshape now prints using pprint
* discover now works for nested dtype numpy arrays
* removes some functions that are not used

### CODE REVIEW

**Comment by cpcloud** [comment]
@mrocklin any comments here? 

most important commits are:
* https://github.com/cpcloud/datashape/commit/67ec34ef33a8eb3c3decef0af9ae07f81b0892a2
* https://github.com/cpcloud/datashape/commit/4e3936cbd352784c008b167e1410ad52ea1ba9df

**Comment by cpcloud** [comment]
i tried to be a bit more surgical with my commits because of the "cleanup" commits

**Comment by mrocklin** [comment]
Seems fine to me.  My brain is mostly jello right now though.

Regarding commit practices (totally unrelated to this PR):  Looking at the commits you mentioned made me wonder if its better to keep tests and code in the same commit so that future readers don't have to cross-reference.

I've recently become very lazy in my git practices though, so I'm not really in a position to make judgments.

**Comment by cpcloud** [comment]
> if its better to keep tests and code in the same commit so that future readers don't have to cross-reference.

ah, yes. the reason i don't do it that way, is so that i can

1. commit the test
2. run it to make sure it fails
3. write the code that fixes the bug
4. test now passes

otherwise i have to stash and i've lost work that way in the past

**Comment by mrocklin** [comment]
Hrm, I would do the same thing, but replacing the word `commit` with `write` in the first line, I would then commit at the end.  I probably don't have the same setup as you do though or something.

**Comment by cpcloud** [comment]
sometimes i write the code first, left that detail out :)

**Comment by mrocklin** [comment]
Alrighty

**Pull request merged**
