### PR TITLE
discover on long list only looks at first fifty elements

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by cpcloud** [comment]
@mrocklin what's the status on this?

**Comment by mrocklin** [comment]
Status was probably that I wasn't sure I wanted it in.  Still not sure; could go either way.

**Comment by mrocklin** [comment]
Or rather, I'll be fine if this gets closed or merged.

**Comment by cpcloud** [comment]
i'd be happy to merge this if there was a parameter `n=50` that let users control the length at which this behavior occurs

**Comment by cpcloud** [comment]
closing for now. i'm not sure that i'd want this as the default behavior. @mrocklin please reopen if you feel strongly about it

**Pull request closed without merging**
